INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('1', 'Segunda', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('2', 'Segunda', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('3', 'Segunda', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('4', 'Segunda', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('5', 'Segunda', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('6', 'Terça', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('7', 'Terça', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('8', 'Terça', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('9', 'Terça', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('10', 'Terça', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('11', 'Quarta', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('12', 'Quarta', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('13', 'Quarta', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('14', 'Quarta', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('15', 'Quarta', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('16', 'Quinta', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('17', 'Quinta', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('18', 'Quinta', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('19', 'Quinta', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('20', 'Quinta', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('21', 'Sexta', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('22', 'Sexta', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('23', 'Sexta', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('24', 'Sexta', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('25', 'Sexta', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('26', 'Sabado', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('27', 'Sabado', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('28', 'Sabado', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('29', 'Sabado', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('30', 'Sabado', 'Ceia');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('31', 'Domingo', 'Pequeno Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('32', 'Domingo', 'Almoço');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('33', 'Domingo', 'Lanche');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('34', 'Domingo', 'Jantar');
INSERT INTO `medlar`.`horario` (`idHorario`, `dia`, `periodo`) VALUES ('35', 'Domingo', 'Ceia');
